### ISSUE TITLE
Water Breathing Crash

### ISSUE THREAD

**Issue by frederic-orlando** [Tigereye504/chest-cavity#4]
Hello, i encountered an issue

I'm using your mod in my server (fabric 1.16.2)

The player get disconnected when using water breathing potion
And get disconnected again after joining because the water breathing effect still exist
 

Here is the log from the server

[12:42:24] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:55703[12:42:24] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:55703net.minecraft.class_148: Ticking player at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47) ~[?:?] at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:492) ~[?:?] at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:207) ~[?:?] at net.minecraft.network.ClientConnection.tick(ClientConnection:234) ~[?:?] at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?] at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[intermediary-server.jar:?] at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:303) ~[?:?] at net.minecraft.server.MinecraftServer.tick(MinecraftServer:808) ~[intermediary-server.jar:?] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:667) ~[intermediary-server.jar:?] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254) ~[intermediary-server.jar:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1291.method_5573()Z at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.47) ~[?:?] at net.tigereye.chestcavity.listeners.ChestCavityListener.TickLiver(ChestCavityListener.java:237) ~[chestcavity-1.1.0.jar:?] at net.minecraft.entity.player.PlayerEntity.baseTick(PlayerEntity:3801) ~[?:?] at net.minecraft.entity.Entity.tick(Entity:431) ~[?:?] at net.minecraft.entity.LivingEntity.tick(LivingEntity:2209) ~[?:?] at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:274) ~[?:?] at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:428) ~[?:?] ... 9 more

**Comment by Tigereye504** [comment]
Issue Resolved- it was in issue with the liver calling a client-only function on the server. fix included in 1.2.2
